package fs;
import static fs.Fs.countno;
import javax.swing.JOptionPane;
import static fs.Fs.recs;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.IOException;
import javax.swing.*;
/**
 *
 * @author Rutuja Rajesh
 */
public class search extends javax.swing.JFrame{

    /**
     * Creates new form search
     */
    public search() {
        initComponents();
        setTitle("SEARCH");
        
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(817, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("SEARCH");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(270, 60, 160, 37);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Doctor id");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 180, 63, 17);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(380, 170, 128, 28);

        jButton1.setFont(new java.awt.Font("Rod", 1, 14)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(180, 330, 92, 48);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(420, 330, 76, 48);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajesh\\Downloads\\Screenshot_2018-05-10-19-39-03-599.jpeg")); // NOI18N
        jLabel3.setText("dd");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 820, 600);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 820, 600);

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String name,fees,spec,phone,count;
        String[] nodes=new String[100];
        btree b = new btree();
        int choice=1,key=1,no = 0,rkey;
        try {
            no=countno();

            System.out.println("No. of records: "+no+"\n");
            for(int i=0;i<=no;i++)
            recs[i]=new records();
            BufferedReader f3 = new BufferedReader(new FileReader("C:\\Users\\Rajesh\\Documents\\NetBeansProjects\\fs\\bplus.txt"));
            for(int i=0;i<=no;i++)
            {
                String lineRead=f3.readLine();
                String [] st = lineRead.split("\\|");
                recs[i].keyf=st[0];
                recs[i].name=st[1];
                recs[i].fee=st[2];
                recs[i].spec=st[3];
                recs[i].phone=st[4];
                rkey=Integer.valueOf(recs[i].keyf);
                b.insert(rkey);
            }
            f3.close();

            key=Integer.valueOf(jTextField1.getText());
            b.search(key);
            f3=new BufferedReader(new FileReader("C:\\Users\\Rajesh\\Documents\\NetBeansProjects\\fs\\bplus.txt"));
            for(int i=0;i<no;i++)
            {
                String lineRead=f3.readLine();
                String [] t=lineRead.split("\\|");
                recs[i].keyf=t[0];
                recs[i].name=t[1];
                recs[i].fee=t[2];
                recs[i].spec=t[3];
                recs[i].phone=t[4];
                rkey=Integer.valueOf(recs[i].keyf);

                if(key==rkey)
                {
                    new searchresult(key,recs[i].name,recs[i].fee,recs[i].spec,recs[i].phone).setVisible(true);
                    this.setVisible(false);
                }
            }
            f3.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane," not success");
            Logger.getLogger(insert.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
        
        // TODO add your handling code here:
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
new options().setVisible(true);        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
records recs[]=new records[100];
/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}
